name: "release-notes-from-pullrequests-action"
description: "Create release notes based on pull requests"
inputs:
  token:
    description: "Github token"
    required: false
    default: "${{ github.token }}"
  repository:
    description: "Target repository"
    required: false
    default: "${{ github.repository }}"
  next-tag:
    description: "Next Release Tag"
    required: true
outputs:
  release-notes:
    description: "Generated Release Notes from pull requests"
    value: ${{ steps.create-release-notes-from-pullrequests.outputs.release-notes }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1.3.4
      with:
        virtualenvs-create: false
    - name: Install dependencies
      run: poetry install
      working-directory: "${{ github.action_path }}"
      shell: bash
    - name: Create Release Notes from Pull Requests
      id: create-release-notes-from-pullrequests
      run: |
        {
          echo 'release-notes<<EOF'
          poetry run release-notes-from-pullrequests
          echo EOF
        } >> "$GITHUB_OUTPUT"
      working-directory: "${{ github.action_path }}"
      env:
        NEXT_RELEASE_TAG: "${{ inputs.next-tag }}"
        GITHUB_REPOSITORY: "${{ inputs.repository }}"
        GITHUB_TOKEN: "${{ inputs.token }}"
      shell: bash
